### ISSUE TITLE
Regarding Rows count

### ISSUE THREAD

**Issue by achinverma** [ATHBK/AvatarTinderView#1]
Hi , i am using this library in my app. i have used below code which give me this out put , plz see in the screen shot .
**In the second row , it shows me 3 item horizontally. 
But i need 4 items , it is my requirement , please suggest me how can i achieve this**  

![device-2017-11-27-112333](https://user-images.githubusercontent.com/2811593/33252644-6e83911e-d365-11e7-9b84-66d337b41577.png)

```
 <com.athbk.avatarview.TinderRecyclerView
        android:id="@+id/recyclerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:spanCount="3"
        app:numberColoum="3">
```

My requirement is below , 
in the 1st row  - 1 item 
2nd row - 4 items

![pics](https://user-images.githubusercontent.com/2811593/33252738-f230cacc-d365-11e7-8f56-30c4f803c1d2.png)

**Comment by ATHBK** [comment]
Hi achinverma, thanks you to using my libary.
For your requirement, you can use:
```
 <com.athbk.avatarview.TinderRecyclerView
        android:id="@+id/recyclerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:spanCount="4"
        app:numberColoum="4">
```
spanCount: number span of item 1
numberColoum: number of coloum.

I hope can help you  !
Best regards,

**Comment by achinverma** [comment]
@ATHBK  , Thanks 
it works :+1:
