### ISSUE TITLE
Regarding drag and drop from small image to large image

### ISSUE THREAD

**Issue by achinverma** [ATHBK/AvatarTinderView#2]
Hi ,
I have a question regarding drag and drop from small image to large image , it is not working when i drag small image and drop the small image to large image it is not replacing the view , 
I have attached a video , as you can see. please guide me how to fix this issue

Video Url:
https://www.dropbox.com/s/5xiysw40yh8mo6s/20171127_123658.mp4?dl=0

**Comment by ATHBK** [comment]
Hi achinverma,
I extend ItemTouchHelper for event drag and drop so if you will want to replace small image to large image, you move small image to top or right edge of large image. It is working.
[![Demo](https://media.giphy.com/media/l2RnCkiwCYEK1knsI/giphy.gif)]
Demo:
https://media.giphy.com/media/l2RnCkiwCYEK1knsI/giphy.gif

**Comment by achinverma** [comment]
@ATHBK , okay, so it will work when i drop the image  to top or right edge of large image.
and if i want to make change in the logic, i mean , if i drop the small image to centre of large image then i want to perform the replace functionality , please tell me where should i change in your code?
